name: Create Tag on Codeberg Mirror

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  CODEBERG_API_KEY: ${{ secrets.CODEBERG_API_KEY }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  REPO_OWNER: ${{ secrets.REPO_OWNER }}
  TARGET_BRANCH: ${{ github.ref_name }}

jobs:
  tag:
    name: Create release tag on Codeberg
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version
        id: get-current-ver
        run: |
            echo "TAG_VERSION=$(awk '/package/, /dependencies/' Cargo.toml | grep -Po '([0-9]\.[0-9]\.[0-9])')" >> "$GITHUB_ENV"

      - name: Check version
        run: |
            echo "tag-ver: $TAG_VERSION, branch: $TARGET_BRANCH, repo: $REPO_NAME"

      - name: Create tag in Codeberg
        env:
          TAG_PREFIX: 'v'
        if: ${{ env.TAG_VERSION != null && env.TARGET_BRANCH != null}}
        run: |
          curl -X 'POST' \
            'https://codeberg.org/api/v1/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/tags' \
            -H 'accept: application/json' \
            -H 'Authorization: token ${{ env.CODEBERG_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{
            "tag_name": "${{ env.TAG_PREFIX }}${{ env.TAG_VERSION }}",
            "target": "${{ env.TARGET_BRANCH }}"
          }'
