name: Create Tag

on:
  # Disable tagging on Github. See issue: https://codeberg.org/mavu072/cacio-term/issues/8
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    name: Create release tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        uses: butlerlogic/action-autotag@1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          strategy: regex
          root: "Cargo.toml"
          regex_pattern: |
              version\s?=\s?\"([0-9\.]*)\"
          tag_prefix: "v"
